### ISSUE TITLE
[Tips] No release yet?

### ISSUE THREAD

**Issue by Quorafind** [thex3family/obsidian-success-plan#1]

**Comment by joshwingreene** [comment]
Hey. Not yet. This is my first time creating a release and packaging up files manually. So, give me some time. However, if you are a developer or know how to code, there's nothing stopping you from (1) downloading the project (2) putting it into your vault's .obsidian directory (3) opening the plugin's directory (4) running yarn (5) running yarn dev (6) enabling the plugin (6) making use of the plugin.

**Comment by joshwingreene** [comment]
Hello again, The release has been published. Here's the release and the PR: [Release](https://github.com/thex3family/obsidian-success-plan/releases), [PR](https://github.com/obsidianmd/obsidian-releases/pull/668)
