### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by beaussan** [thex3family/obsidian-success-plan#2]
Hi,

First of all, I find this plugin and the idea behind it really good !

I know the notion integration is optional, but I find it interesting and I want to try it out.

However, I have an issue with this plugin, it's sending my private notion key and db id to your n8n endpoint (see https://github.com/joshwingreene/obsidian-success-plan/blob/main/ReactApp.tsx#L27 ), and with this pattern, the notion key is stored in the .obsidian/plugins/pluginName.json config, thus exposing the notion key.

To recap : 
* The notion key is stored in plain text in the settings file
* The notion key and db id is send to a n8n workflow that we don't know what is going on
* The more folks use this plugin, the more your n8n bill will grow, I don't know if you are ok with that (I doubt), but if one day it's too much for you, that you can stop providing the n8n endpoint

Here is some napkin math : 
100 users
10 daily tasks
30 day in a month  (mean)
= 30 000 invocation, that means already the pro 120€/month

Proposed solution : 
* Add the ability to provide your own n8n endpoint (either cloud or selfhosted) in the settings, could be optional but if it's optional, there should be a warning still if using the public one
* Have the json of the n8n workflow, or publish it on the n8n workflow public listing and linking it in the docs to host it easily

**Comment by joshwingreene** [comment]
Hey! Thanks for the praise and for raising this concern. I actually didn't know that a settings file is created when you customize a plugin's settings.

When it comes to that issue, I don't believe many people would have access to that file. If you use Obsidian Sync, everything is encrypted. So, at least with that option, you would be safe. However, I know that a lot of people aren't using that option. So, at the very least, there should be a disclaimer about that. Do you have any suggestions on how to make this safer? 

When it comes to sending the notion integration key and db id, that's how things are done in regards to the Make Work Fun app. People basically have to trust Conrad (the founder of Co-x3 and the Make Work Fun app)(https://conradlin.com/) to keep everything secure. For reference, Make Work fun uses Supabase for the backend. So, that's where people's key and db id are stored. As for this plugin, your key is only used to push your completed wins to the Notion database that is identified via the database id. Besides that, it doesn't store anything. But, it is necessary to trust Conrad with your key and database id if you are using the Make Work Fun app.

As for the n8n bill, I actually used the highest tier trial initially. Thanks for the napkin math. For now, I'll turn the Make Work Fun feature off. However, I did save the workflow. So, I will likely follow your suggestion if I decide to go with your proposed solution.

**Comment by joshwingreene** [comment]
Hello again, Besides disabling the Make Work Fun feature, the plan is to remove the n8n and Notion integration and have the plugin directly post wins to the Make Work Fun app. So, this concern will no longer be an issue. This will be online in the next release.
